trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: name
  value: 'sudhakar'

- group: airplan-variables

steps:
- script: |
    echo $(name)

- script: |
    echo $(age)

- script: |
    echo $(javaVersion)
  