apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-outbound
spec:
  podSelector:
    matchLabels:
      app: myapp3
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.224.0.0/16
   
