name: Build and push docker image to acr
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - run: |
          docker build -t sampleapp:4.0.0 Applicationcode
          docker tag sampleapp:4.0.0 ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:4.0.0
          az login --service-principal --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} --tenant 3d993c04-128c-48de-ba4a-1afbb101cfa1
          az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:4.0.0
          docker images
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main  # Use stable version
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'  # Optionally specify the version you want
      - name: Deployment to AKS
        run: | 
             az login --service-principal --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }} --tenant 3d993c04-128c-48de-ba4a-1afbb101cfa1
             az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
             az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP1 }} --name ${{ secrets.CLUSTER_NAME }} --overwrite-existing
             az aks update -n ${{ secrets.CLUSTER_NAME }} -g ${{ secrets.RESOURCE_GROUP1 }} --attach-acr ${{ secrets.ACR_NAME }}
             kubectl apply -f kubemanifestfile/deployment.yml 


           
      
